name: Deploy
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH env
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa # config private key
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 5000 cdn-src.honeyworks.info >> ~/.ssh/known_hosts
      - name: Deploy 🚀 To Server
        run: |
          ssh -p 5000 Administrator@cdn-src.honeyworks.info "\
          cd C:\project\HoneyWorks-Info-i18n && \
          git pull && \
          qshell qupload -c 100 C:\project\HWPL_api_backend\tools\qshell\sync-i18n.config.json"
    
